[CarlaSettings]
carla_path = D:/fourj/apps/carla/CARLA_0.9.16/CarlaUE4.exe
spawn_x = -1930
spawn_y = 48.25
spawn_z = 0.3
spawn_yaw = 0
python_path = D:/fourj/apps/miniconda/envs/carla/python.exe

[TrafficLight]
green_time = 30.0
yellow_time = 3.0
red_time = 30.0
# 设置为 true 则应用时间减半，加速交通流
accelerate_traffic = false

[Memo]
notes = gaoshu3800坐标：
	x=-1930
	y=48.25
	z=0.3
	yaw=0
	
	Town04坐标：
	x=5
	y=27
	z=12
	yaw=0

